version: '3.9'

services:
  app:
    build:
      context: .
    container_name: python-app
    volumes:
      - .:/app
    command: python3 /app/weather_db.py
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:0000@db:5432/weather_db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: weather_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
